#!/usr/bin/env bash

ctrl=$(buildah from cybermaggedon/partygate-base)

rm -f serve
make serve

buildah run "$ctrl" -- dnf install -y libgo
buildah add "$ctrl" serve /usr/local/bin/serve
buildah add "$ctrl" lodlive /usr/local/web/

buildah config --workingdir /usr/local/web/ "$ctrl"
buildah config --cmd /usr/local/bin/serve "$ctrl"
buildah config --port 8080 "$ctrl"

buildah commit "$ctrl" $1

