
name: Test pull request

on:
  pull_request:

permissions:
  contents: read

jobs:

  container-push:

    name: Validate data
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt update &&
            sudo apt install -y redland-utils librdf-storage-sqlite &&
            sudo apt install python3-rdflib

      - name: Test assembly of RDF data
        run: make curate

